INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table ronde', 'blanc', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table rectangle', 'noir', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table rectangle', 'blanc', '100$', 'static/photo/privée/en_privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table de bistriot', 'blanc', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table ronde', 'bleu', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'doré', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table rectangle', 'noir', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table ronde', 'doré', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table de bistriot', 'noir', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table rectangle', 'blanc', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'noir', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table haute et mange-debout', 'bleu', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table haute et mange-debout', 'rouge', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table ronde', 'blanc', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table rectangle', 'blanc', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table rectangle', 'rouge', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table de bistriot', 'bleu', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table ronde', 'bleu', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'noir', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table haute et mange-debout', 'bleu', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table ronde', 'blanc', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table de bistriot', 'bleu', '100$', 'static/photo/privée/en_privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table rectangle', 'noir', '100$', 'static/photo/privée/en_privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table ronde', 'bleu', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'rouge', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table haute et mange-debout', 'noir', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table rectangle', 'bleu', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table de bistriot', 'doré', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table haute et mange-debout', 'rouge', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table ronde', 'rouge', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'rouge', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table ronde', 'blanc', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table de bistriot', 'bleu', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table rectangle', 'blanc', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table ronde', 'blanc', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table de bistriot', 'blanc', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table ronde', 'noir', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table de bistriot', 'bleu', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table de bistriot', 'rouge', '100$', 'static/photo/privée/en_privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'noir', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table rectangle', 'rouge', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table de bistriot', 'noir', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table ronde', 'noir', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table rectangle', 'doré', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table haute et mange-debout', 'bleu', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table haute et mange-debout', 'noir', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table de bistriot', 'doré', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table haute et mange-debout', 'rouge', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table de bistriot', 'noir', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table de bistriot', 'doré', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table haute et mange-debout', 'noir', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table rectangle', 'noir', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table de bistriot', 'noir', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table ronde', 'noir', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'doré', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table haute et mange-debout', 'blanc', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table haute et mange-debout', 'blanc', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table de bistriot', 'noir', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table ronde', 'noir', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table rectangle', 'doré', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table rectangle', 'bleu', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table haute et mange-debout', 'blanc', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table de bistriot', 'doré', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table ronde', 'rouge', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table de bistriot', 'blanc', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table de bistriot', 'noir', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table haute et mange-debout', 'doré', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table rectangle', 'noir', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table haute et mange-debout', 'blanc', '100$', 'static/photo/privée/en_privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table de bistriot', 'bleu', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table ronde', 'doré', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table rectangle', 'bleu', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon2', 'table rectangle', 'doré', '130$', 'static/photo/balcon/balcon2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table de bistriot', 'bleu', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table ronde', 'doré', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table haute et mange-debout', 'rouge', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table ronde', 'rouge', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'bleu', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table ronde', 'bleu', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table rectangle', 'noir', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table ronde', 'doré', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table rectangle', 'doré', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer2', 'table de bistriot', 'rouge', '150$', 'static/photo/mer/mer2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table ronde', 'doré', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table ronde', 'rouge', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table rectangle', 'blanc', '100$', 'static/photo/privée/en_privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table haute et mange-debout', 'rouge', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table de bistriot', 'doré', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table ronde', 'blanc', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table de bistriot', 'doré', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique1', 'table rectangle', 'rouge', '50$', 'static/photo/publique/pubique1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table ronde', 'blanc', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('balcon1', 'table rectangle', 'doré', '130$', 'static/photo/balcon/balcon1.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en publique2', 'table rectangle', 'bleu', '50$', 'static/photo/publique/publique2.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table de bistriot', 'doré', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table haute et mange-debout', 'bleu', '100$', 'static/photo/privée/en_privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table de bistriot', 'doré', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('vue de mer1', 'table ronde', 'noir', '150$', 'static/photo/mer/mer.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée2', 'table ronde', 'doré', '100$', 'static/photo/privée/privé.jpg');
INSERT INTO resto (emplacement, type_table, couleur_nappe, cout_reservation, imgs) VALUES ('en privée1', 'table ronde', 'rouge', '100$', 'static/photo/privée/en_privé.jpg');
