CREATE TABLE IF NOT EXISTS site_reservation_voiture (
        id INT PRIMARY KEY AUTO_INCREMENT,
        marque VARCHAR(50) NOT NULL,
        modele VARCHAR(50)  NOT NULL,
        nombre_places INT  NOT NULL,
        boite_vitesse VARCHAR(50)  NOT NULL,
        carburant VARCHAR(50)  NOT NULL,
        climatisation BOOLEAN DEFAULT True,
        couleur VARCHAR(20)  NOT NULL,
        annee_production INT  NOT NULL,
        cout_journalier_location VARCHAR(50) NOT NULL,
        image_path VARCHAR(255) NOT NULL,
        disponible BOOLEAN DEFAULT True
    );
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 5, 'manuelle', 'electrique', True, 'bleu', 2020, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Corolla', 2, 'automatique', 'essence', False, 'gris', 2014, '100$', 'reservation/media-voiture/v.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Mustang', 5, 'manuelle', 'diesel', False, 'rouge', 2016, '170$', 'reservation/media-voiture/v4.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 2, 'manuelle', 'electrique', False, 'gris', 2020, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 5, 'automatique', 'diesel', True, 'gris', 2020, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 2, 'manuelle', 'electrique', True, 'blanc', 2019, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'diesel', False, 'blanc', 2017, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 2, 'manuelle', 'diesel', False, 'gris', 2019, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Corolla', 2, 'manuelle', 'essence', True, 'blanc', 2014, '100$', 'reservation/media-voiture/v.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 5, 'manuelle', 'essence', True, 'rouge', 2019, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', 'X6', 5, 'automatique', 'essence', True, 'blanc', 2017, '170$', 'reservation/media-voiture/v12.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'automatique', 'diesel', False, 'gris', 2020, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', 'X5', 5, 'manuelle', 'electrique', True, 'bleu', 2020, '110$', 'reservation/media-voiture/v9.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'essence', True, 'blanc', 2018, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Focus', 2, 'manuelle', 'essence', False, 'rouge', 2014, '150$', 'reservation/media-voiture/v3.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 2, 'automatique', 'electrique', False, 'bleu', 2020, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 2, 'manuelle', 'diesel', True, 'gris', 2017, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Focus', 5, 'manuelle', 'essence', True, 'rouge', 2015, '150$', 'reservation/media-voiture/v3.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 5, 'automatique', 'diesel', True, 'gris', 2018, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '3 Series', 2, 'automatique', 'electrique', False, 'rouge', 2021, '80$', 'reservation/media-voiture/v10.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 5, 'automatique', 'diesel', False, 'blanc', 2019, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 5, 'manuelle', 'diesel', False, 'bleu', 2018, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 5, 'automatique', 'electrique', False, 'blanc', 2021, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 5, 'automatique', 'diesel', False, 'blanc', 2020, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'essence', True, 'gris', 2019, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'manuelle', 'electrique', False, 'rouge', 2017, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Polo', 2, 'automatique', 'electrique', True, 'gris', 2016, '50$', 'reservation/media-voiture/v7.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 5, 'manuelle', 'essence', False, 'noir', 2017, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 2, 'automatique', 'electrique', True, 'bleu', 2019, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Corolla', 2, 'automatique', 'diesel', True, 'rouge', 2021, '100$', 'reservation/media-voiture/v.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 5, 'manuelle', 'diesel', True, 'rouge', 2021, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 5, 'automatique', 'essence', False, 'blanc', 2020, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 5, 'manuelle', 'essence', True, 'rouge', 2018, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Polo', 2, 'automatique', 'electrique', False, 'rouge', 2019, '50$', 'reservation/media-voiture/v7.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'automatique', 'essence', False, 'bleu', 2018, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Corolla', 5, 'manuelle', 'essence', True, 'rouge', 2014, '100$', 'reservation/media-voiture/v.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'manuelle', 'essence', False, 'noir', 2016, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', 'X5', 2, 'manuelle', 'essence', True, 'gris', 2020, '110$', 'reservation/media-voiture/v9.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 5, 'manuelle', 'electrique', True, 'gris', 2019, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'automatique', 'electrique', False, 'noir', 2017, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'manuelle', 'electrique', False, 'gris', 2015, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 5, 'manuelle', 'essence', True, 'bleu', 2020, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Polo', 5, 'automatique', 'essence', True, 'noir', 2020, '50$', 'reservation/media-voiture/v7.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'manuelle', 'electrique', False, 'rouge', 2020, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 5, 'manuelle', 'diesel', True, 'rouge', 2021, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', 'X6', 5, 'automatique', 'diesel', False, 'bleu', 2014, '170$', 'reservation/media-voiture/v12.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'electrique', False, 'gris', 2021, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 2, 'automatique', 'electrique', False, 'rouge', 2020, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'essence', False, 'noir', 2017, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'automatique', 'diesel', True, 'gris', 2021, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', 'X6', 5, 'manuelle', 'diesel', False, 'rouge', 2015, '170$', 'reservation/media-voiture/v12.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'automatique', 'electrique', False, 'bleu', 2020, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 2, 'automatique', 'essence', False, 'noir', 2020, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 5, 'manuelle', 'essence', True, 'bleu', 2019, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 2, 'manuelle', 'essence', True, 'rouge', 2018, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'manuelle', 'essence', True, 'gris', 2019, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'automatique', 'diesel', False, 'blanc', 2018, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 2, 'automatique', 'electrique', True, 'noir', 2021, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', 'X5', 2, 'manuelle', 'essence', True, 'rouge', 2016, '110$', 'reservation/media-voiture/v9.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '3 Series', 5, 'manuelle', 'diesel', True, 'bleu', 2017, '80$', 'reservation/media-voiture/v10.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 5, 'manuelle', 'electrique', False, 'rouge', 2021, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Polo', 2, 'manuelle', 'essence', True, 'blanc', 2020, '50$', 'reservation/media-voiture/v7.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 5, 'manuelle', 'diesel', True, 'rouge', 2017, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'manuelle', 'essence', False, 'noir', 2014, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Focus', 2, 'automatique', 'diesel', True, 'bleu', 2015, '150$', 'reservation/media-voiture/v3.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 2, 'manuelle', 'electrique', False, 'bleu', 2021, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'manuelle', 'essence', False, 'blanc', 2014, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Mustang', 5, 'automatique', 'essence', False, 'bleu', 2020, '170$', 'reservation/media-voiture/v4.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'essence', True, 'bleu', 2017, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 5, 'automatique', 'diesel', False, 'blanc', 2019, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'manuelle', 'electrique', True, 'blanc', 2015, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'manuelle', 'diesel', True, 'blanc', 2016, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '3 Series', 2, 'manuelle', 'essence', True, 'noir', 2014, '80$', 'reservation/media-voiture/v10.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '3 Series', 5, 'automatique', 'diesel', True, 'gris', 2014, '80$', 'reservation/media-voiture/v10.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Focus', 2, 'automatique', 'diesel', True, 'bleu', 2017, '150$', 'reservation/media-voiture/v3.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'manuelle', 'diesel', True, 'gris', 2020, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 2, 'automatique', 'electrique', False, 'blanc', 2019, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 2, 'automatique', 'essence', False, 'bleu', 2017, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Mustang', 2, 'automatique', 'diesel', True, 'gris', 2020, '170$', 'reservation/media-voiture/v4.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', 'X6', 5, 'manuelle', 'essence', False, 'bleu', 2014, '170$', 'reservation/media-voiture/v12.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'diesel', True, 'rouge', 2016, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 5, 'automatique', 'diesel', False, 'blanc', 2014, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 2, 'manuelle', 'essence', True, 'gris', 2014, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Golf', 5, 'manuelle', 'diesel', True, 'bleu', 2015, '80$', 'reservation/media-voiture/v6.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 2, 'manuelle', 'electrique', False, 'bleu', 2016, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'automatique', 'electrique', True, 'noir', 2018, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 2, 'manuelle', 'diesel', False, 'gris', 2019, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 5, 'automatique', 'electrique', False, 'rouge', 2020, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Polo', 5, 'automatique', 'essence', False, 'gris', 2015, '50$', 'reservation/media-voiture/v7.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Polo', 5, 'manuelle', 'electrique', False, 'gris', 2020, '50$', 'reservation/media-voiture/v7.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '7 Series', 5, 'automatique', 'essence', False, 'gris', 2017, '120$', 'reservation/media-voiture/v11.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Polo', 5, 'manuelle', 'diesel', True, 'gris', 2019, '50$', 'reservation/media-voiture/v7.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'Camry', 2, 'manuelle', 'electrique', False, 'bleu', 2018, '120$', 'reservation/media-voiture/v1.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Volkswagen', 'Passat', 2, 'manuelle', 'diesel', True, 'blanc', 2014, '100$', 'reservation/media-voiture/v8.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Focus', 5, 'manuelle', 'essence', True, 'noir', 2017, '150$', 'reservation/media-voiture/v3.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Explorer', 2, 'automatique', 'diesel', False, 'blanc', 2018, '100$', 'reservation/media-voiture/v5.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '3 Series', 2, 'automatique', 'essence', True, 'gris', 2015, '80$', 'reservation/media-voiture/v10.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('BMW', '3 Series', 2, 'manuelle', 'essence', True, 'blanc', 2015, '80$', 'reservation/media-voiture/v10.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Toyota', 'RAV4', 2, 'manuelle', 'diesel', False, 'noir', 2015, '130$', 'reservation/media-voiture/v2.jpg', True);
INSERT INTO site_reservation_voiture (marque, modele, nombre_places, boite_vitesse, carburant, climatisation, couleur, annee_production, cout_journalier_location, image_path, disponible) VALUES ('Ford', 'Mustang', 2, 'automatique', 'diesel', False, 'bleu', 2020, '170$', 'reservation/media-voiture/v4.jpg', True);
