# Generated by Django 4.2.1 on 2023-05-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0002_suite_delete_hotel_delete_voiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='image',
            field=models.ImageField(upload_to='media_suites/'),
        ),
    ]
