# Generated by Django 4.2.1 on 2023-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media_suite'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='image',
            field=models.ImageField(upload_to='media_suite/'),
        ),
    ]
