# Generated by Django 4.2.1 on 2023-06-10 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_reservation', '0006_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_reservation.Suite', db_column='suite_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
