# Generated by Django 4.2.1 on 2023-06-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0007_reservation_suite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
