# Generated by Django 4.2.1 on 2023-06-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0008_alter_suite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_suite',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_reservation.suite'),
        ),
    ]
